---
version: "3.9"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: "${DB_NAME:-wordpress}"
      MYSQL_USER: "${DB_USER:-wordpress}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-wordpress}"
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: ["./:/var/www/html"]
    ports:
      - "${PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER:-wordpress}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:-wordpress}"
      WORDPRESS_DB_NAME: "${DB_NAME:-wordpress}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX:-wordpress}"
volumes:
  db_data: {}
